language: php
sudo: required

services:
  - memcached
  - redis-server
  - mysql

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
#  - '7.3'

matrix:
  fast_finish: true
  allow_failures:
#    - php: '7.3'

mysql:
  database: phwoolcon_test
  username: travis
  encoding: utf8mb4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon
    - $HOME/pecl_cache

before_install:
  - sudo apt-get update -qq
  # Install Beanstalkd (Queue support) and Postfix (SMTP mailer support)
  - sudo apt-get install -qq beanstalkd postfix
  # Use test mail server
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - sudo service beanstalkd restart
  - pecl channel-update pecl.php.net
  - phpenv config-add tests/travis/php-ext.ini
  # Install Extensions
  - bash bin/ci-install-extensions
  - composer install --prefer-source --no-interaction

before_script:
  # Create database
  - mysql -uroot -e 'CREATE DATABASE `phwoolcon_test` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;'
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%';";
  # Print Phalcon and Swoole info
  - php --ri phalcon
  - php --ri swoole

script:
  # Check code style
  - vendor/bin/phpcs
  # Running unit test
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
  # Collect code coverage
  # If need cache, check ETAG
  # ETAG=( $(curl -IL https://scrutinizer-ci.com/ocular.phar 2>/dev/null | grep -i etag) ); echo ${ETAG[1]}
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

branches:
  #Don't build tags
  except:
  - /^v\d/
